version: "3.8"

services:
  node1:
    image: ruimarinho/bitcoin-core:24
    container_name: btc-node1
    volumes:
      - ./node1:/bitcoin
    command:
      -printtoconsole -regtest -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0
      -rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD}
      -port=18444 -rpcport=18443
    environment:
      RPC_USER: ${RPC_USER}
      RPC_PASSWORD: ${RPC_PASSWORD}
    networks:
      - btcnet

  node2:
    image: ruimarinho/bitcoin-core:24
    container_name: btc-node2
    volumes:
      - ./node2:/bitcoin
    command:
      -printtoconsole -regtest -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0
      -rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD}
      -port=19444 -rpcport=19443
    environment:
      RPC_USER: ${RPC_USER}
      RPC_PASSWORD: ${RPC_PASSWORD}
    networks:
      - btcnet

networks:
  btcnet:
