version: "3.8"

services:
  node1:
    image: ruimarinho/bitcoin-core:24.0
    container_name: node1
    command:
      - -regtest
      - -conf=/bitcoin.conf
    volumes:
      - ./node1/bitcoin.conf:/bitcoin.conf
    networks:
      - bitcoin
    environment:
      - RPC_USER=${RPC_USER}
      - RPC_PASSWORD=${RPC_PASSWORD}

  node2:
    image: ruimarinho/bitcoin-core:24.0
    container_name: node2
    command:
      - -regtest
      - -conf=/bitcoin.conf
    volumes:
      - ./node2/bitcoin.conf:/bitcoin.conf
    networks:
      - bitcoin
    environment:
      - RPC_USER=${RPC_USER}
      - RPC_PASSWORD=${RPC_PASSWORD}

networks:
  bitcoin:
    driver: bridge
